Repository ucalyptus/Spotify-Recommendation-Engine, pull requests merged in 2020-04, with the labels that each got.

#50 Language.yml
  .github/workflows/foul-language.yml
Labels: gssoc20, medium

#48 Greetings.yml
  .github/workflows/greetings.yml
Labels: easy, gssoc20

#56 Create spellcheck.yml
  .github/workflows/spellcheck.yml
Labels: easy, gssoc20

#58 Create weekly.yml
  .github/workflows/weekly.yml
Labels: gssoc20

#59 Create wip-action.yml
  .github/workflows/wip-action.yml
Labels: easy, gssoc20

#46 First refactor PR
  __init__.py
  data-structures.py
  data-structures/DataMap.py
  data-structures/DenseMatrix.py
  data-structures/DenseVector.py
  data-structures/Pair.py
  data-structures/Rating.py
  data-structures/SparseMatrix.py
  data-structures/SparseVector.py
  dataset.py
  model.py
  train.py
  utils.py
Labels: gssoc20, hard

#62 updated contribution guidelines in the readme
  README.md
Labels: easy, gssoc20

#60 Create action-forge.yml
  .github/workflows/action-forge.yml
Labels: gssoc20, medium

#61 Create pr-greet-message.yml
  .github/workflows/pr-greet-message.yml
Labels: easy, gssoc20

#67 Contributor table for GSSOC
  README.md
Labels: gssoc20, medium

#63 Add sample data from last.fm
  user_artists.dat
Labels: enhancement, gssoc20, medium

#68 Refactored Notebook
  .DS_Store
  Refactored Notebooks/api.py
  Refactored Notebooks/dataset.py
  Refactored Notebooks/init.py
  Refactored Notebooks/recommender.py
  Refactored Notebooks/utils.py
Labels: gssoc20, medium

#69 Added utils.py
  utils.py
Labels: gssoc20, hard
